import { Category, Customer, Product, SystemSettings, Table } from '@/types';

export const INITIAL_SETTINGS: SystemSettings = {
  restaurantName: 'The Royal Palette',
  tagline: 'A Symphony of Royal Flavors & Contemporary Elegance',
  currency: '৳',
  currencyCode: 'BDT',
  address: 'Plot 42, Road 11, Block D, Gulshan-2, Dhaka 1212',
  phone: '+880 1711-234567',
  email: 'concierge@royalpalette.com.bd',
  binNumber: 'BIN-002938471-0102',
  vatPercent: 0,
  serviceChargePercent: 0,
  loyaltyPointsPer100BDT: {
    BRONZE: 1,      // 1 point per ৳100 spent
    SILVER: 1.5,    // 1.5 points per ৳100 spent
    GOLD: 2,        // 2 points per ৳100 spent
    ROYAL: 3,       // 3 points per ৳100 spent
  },
  loyaltyRedemptionRate: 1, // 1 point = ৳1 discount
  tierSpendThresholds: {
    SILVER: 10000,  // ৳10,000 spent to reach Silver
    GOLD: 35000,    // ৳35,000 spent to reach Gold
    ROYAL: 80000,   // ৳80,000 spent to reach Royal Ambassador
  },
  printerType: 'WEB_SERIAL',
  autoKickDrawerOnCash: true,
  drawerKickCodeHex: '1B 70 00 19 FA',
  receiptFooterMessage: 'Thank you for gracing The Royal Palette! Visit again.',
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: "Chef's Royal Signatures",
    slug: 'signatures',
    description: 'Mastercrafted culinary masterpieces infused with rare saffron & spices',
    iconName: 'Crown',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 'cat-2',
    name: 'Kacchi & Biryani Heritage',
    slug: 'biryani',
    description: 'Dum-cooked aromatic basmati rice layered with tender marinated meats',
    iconName: 'Flame',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 'cat-3',
    name: 'Royal Kebabs & Grills',
    slug: 'kebabs',
    description: 'Charcoal-smoked tender cuts marinated in royal Mughal aromatics',
    iconName: 'UtensilsCrossed',
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 'cat-4',
    name: 'Nawabi Curries & Gravies',
    slug: 'curries',
    description: 'Slow-simmered rich cashew and cream infused gravies',
    iconName: 'Soup',
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 'cat-5',
    name: 'Tandoori Breads & Rice',
    slug: 'breads-rice',
    description: 'Fresh clay-oven baked naans, parathas, and zafrani polao',
    iconName: 'Wheat',
    sortOrder: 5,
    isActive: true,
  },
  {
    id: 'cat-6',
    name: 'Royal Starters & Salads',
    slug: 'starters',
    description: 'Crisp, refreshing appetizers to ignite your royal banquet',
    iconName: 'Sparkles',
    sortOrder: 6,
    isActive: true,
  },
  {
    id: 'cat-7',
    name: 'Elixirs & Gourmet Mocktails',
    slug: 'beverages',
    description: 'Artisanal refreshments, saffron coolers, and royal blends',
    iconName: 'GlassWater',
    sortOrder: 7,
    isActive: true,
  },
  {
    id: 'cat-8',
    name: 'Sweet Extravaganza',
    slug: 'desserts',
    description: 'Exquisite desserts crowned with edible silver and pistachio',
    iconName: 'CakeSlice',
    sortOrder: 8,
    isActive: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Grand Shahi Mutton Kacchi',
    banglaName: 'গ্র্যান্ড শাহী খাসির কাচ্চি',
    description: 'Aged basmati rice, tender young mutton chops slow dum-cooked with saffron, aloo bukhara, and mawa.',
    categoryId: 'cat-2',
    price: 680,
    costPrice: 380,
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80',
    dietaryTags: ['CHEF_SPECIAL', 'POPULAR', 'HALAL'],
    isAvailable: true,
    preparationTimeMinutes: 15,
    sortOrder: 1,
    modifierGroups: [
      {
        id: 'mod-portion',
        name: 'Portion Size',
        required: true,
        options: [
          { id: 'opt-reg', name: 'Regular (1 Person + 1 Mutton Piece)', priceDelta: 0 },
          { id: 'opt-large', name: 'Royal Feast (2 Persons + 2 Mutton Pieces)', priceDelta: 580 },
        ],
      },
      {
        id: 'mod-add-ons',
        name: 'Royal Add-ons',
        required: false,
        maxSelections: 3,
        options: [
          { id: 'opt-extra-mutton', name: 'Extra Mutton Shank', priceDelta: 320 },
          { id: 'opt-shahi-egg', name: 'Fried Shahi Egg', priceDelta: 40 },
          { id: 'opt-borhani-cup', name: 'Chilled Borhani Glass (250ml)', priceDelta: 90 },
        ],
      },
    ],
  },
  {
    id: 'prod-2',
    name: 'Saffron Grilled King Prawns Platter',
    banglaName: 'জাফরানি গ্রিলড গলদা চিংড়ি',
    description: 'Jumbo bay of Bengal king prawns brushed with saffron garlic butter and charred over live charcoal.',
    categoryId: 'cat-1',
    price: 1450,
    costPrice: 750,
    imageUrl: 'https://images.unsplash.com/photo-1559742811-822873691df8?w=800&auto=format&fit=crop&q=80',
    dietaryTags: ['CHEF_SPECIAL', 'HALAL', 'GLUTEN_FREE'],
    isAvailable: true,
    preparationTimeMinutes: 20,
    sortOrder: 2,
    modifierGroups: [
      {
        id: 'mod-spice',
        name: 'Spice Level',
        required: true,
        options: [
          { id: 'opt-mild', name: 'Mild Garlic Butter', priceDelta: 0 },
          { id: 'opt-spicy', name: 'Naga Pepper Glaze (Spicy)', priceDelta: 0 },
        ],
      },
    ],
  },
  {
    id: 'prod-3',
    name: 'Nawabi Mutton Rezala',
    banglaName: 'নওয়াবি মাটন রেজালা',
    description: 'Classic Dhaka Mughal curry made with white cashew paste, poppy seeds, mawa, and subtle kewra water aroma.',
    categoryId: 'cat-4',
    price: 620,
    costPrice: 340,
    imageUrl: 'https://images.unsplash.com/photo-1545247181-516773cae7be?w=800&auto=format&fit=crop&q=80',
    dietaryTags: ['HALAL', 'POPULAR'],
    isAvailable: true,
    preparationTimeMinutes: 12,
    sortOrder: 3,
  },
  {
    id: 'prod-4',
    name: 'Smoked Reshmi Malai Tikka',
    banglaName: 'রেশমি মালাই টিক্কা',
    description: 'Boneless chicken breast soaked in hung curd, green cardamom, cheese, and melted cream, charcoal smoked.',
    categoryId: 'cat-3',
    price: 520,
    costPrice: 260,
    imageUrl: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80',
    dietaryTags: ['HALAL', 'POPULAR'],
    isAvailable: true,
    preparationTimeMinutes: 18,
    sortOrder: 4,
    modifierGroups: [
      {
        id: 'mod-dip',
        name: 'Choice of Dip',
        required: false,
        options: [
          { id: 'opt-mint-chutney', name: 'Spicy Mint & Coriander Chutney', priceDelta: 0 },
          { id: 'opt-garlic-mayo', name: 'Smoked Garlic Dip', priceDelta: 30 },
        ],
      },
    ],
  },
  {
    id: 'prod-5',
    name: 'The Royal Palette Signature Platter',
    banglaName: 'রয়্যাল প্যালেট সিগনেচার প্ল্যাটার',
    description: 'Grand assortment of Reshmi Tikka, Galawati Kebab, Zafrani Jheenga, Mutton Seekh, Butter Naan, and signature dips.',
    categoryId: 'cat-1',
    price: 2450,
    costPrice: 1250,
    imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=80',
    dietaryTags: ['CHEF_SPECIAL', 'HALAL'],
    isAvailable: true,
    preparationTimeMinutes: 25,
    sortOrder: 5,
  },
  {
    id: 'prod-6',
    name: 'Zafrani Butter Chicken',
    banglaName: 'জাফরানি বাটার চিকেন',
    description: 'Tandoori roasted chicken pieces simmered in a velvety tomato-fenugreek gravy finished with pure butter.',
    categoryId: 'cat-4',
    price: 580,
    costPrice: 280,
    imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=80',
    dietaryTags: ['HALAL', 'POPULAR'],
    isAvailable: true,
    preparationTimeMinutes: 15,
    sortOrder: 6,
  },
  {
    id: 'prod-7',
    name: 'Truffle Garlic Butter Naan',
    banglaName: 'ট্রাফেল গার্লিক বাটার নান',
    description: 'Hand-stretched dough cooked in clay tandoor, brushed with white truffle oil, roasted garlic, and butter.',
    categoryId: 'cat-5',
    price: 180,
    costPrice: 50,
    imageUrl: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=800&auto=format&fit=crop&q=80',
    dietaryTags: ['VEGETARIAN', 'HALAL'],
    isAvailable: true,
    preparationTimeMinutes: 8,
    sortOrder: 7,
  },
  {
    id: 'prod-8',
    name: 'Zafrani Basmati Polao',
    banglaName: 'জাফরানি বাসমতী পোলাও',
    description: 'Extra-long grain basmati scented with whole spices, Kashmiri saffron, fried golden onions, and toasted cashews.',
    categoryId: 'cat-5',
    price: 320,
    costPrice: 110,
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&auto=format&fit=crop&q=80',
    dietaryTags: ['VEGETARIAN', 'HALAL', 'GLUTEN_FREE'],
    isAvailable: true,
    preparationTimeMinutes: 10,
    sortOrder: 8,
  },
  {
    id: 'prod-9',
    name: 'Crispy Calamari with Naga Tartar',
    banglaName: 'ক্রিস্পি কালামারি উইথ নাগা টারটার',
    description: 'Tender squid rings coated in spiced batter, flash fried, served with hot Naga chili infused tartar dip.',
    categoryId: 'cat-6',
    price: 490,
    costPrice: 220,
    imageUrl: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80',
    dietaryTags: ['HALAL', 'SPICY'],
    isAvailable: true,
    preparationTimeMinutes: 12,
    sortOrder: 9,
  },
  {
    id: 'prod-10',
    name: 'Royal Blue Lagoon Mocktail',
    banglaName: 'রয়্যাল ব্লু লেগুন মকটেল',
    description: 'Blue curacao extract with fresh lemon juice, sparkling tonic, mint sprigs, and edible gold shimmer dust.',
    categoryId: 'cat-7',
    price: 290,
    costPrice: 75,
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=80',
    dietaryTags: ['VEGETARIAN', 'VEGAN', 'GLUTEN_FREE', 'POPULAR'],
    isAvailable: true,
    preparationTimeMinutes: 5,
    sortOrder: 10,
  },
  {
    id: 'prod-11',
    name: 'Traditional Saffron Borhani',
    banglaName: 'ঐতিহ্যবাহী জাফরানি বোরহানি',
    description: 'Creamy spiced yogurt drink blended with mint, coriander, roasted cumin, black pepper, and saffron.',
    categoryId: 'cat-7',
    price: 180,
    costPrice: 60,
    imageUrl: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=800&auto=format&fit=crop&q=80',
    dietaryTags: ['VEGETARIAN', 'HALAL', 'POPULAR'],
    isAvailable: true,
    preparationTimeMinutes: 3,
    sortOrder: 11,
  },
  {
    id: 'prod-12',
    name: '24K Gold Crown Shahi Tukda',
    banglaName: '২৪ ক্যারেট গোল্ড শাহী টুকরা',
    description: 'Crispy ghee-fried brioche soaked in saffron syrup, layered with thick rabri, pistachios, and pure edible 24K gold leaf.',
    categoryId: 'cat-8',
    price: 450,
    costPrice: 180,
    imageUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&auto=format&fit=crop&q=80',
    dietaryTags: ['CHEF_SPECIAL', 'VEGETARIAN', 'HALAL'],
    isAvailable: true,
    preparationTimeMinutes: 10,
    sortOrder: 12,
  },
];

export const INITIAL_TABLES: Table[] = [
  { id: 'tbl-1', tableNumber: 'T-01', capacity: 2, section: 'INDOOR', status: 'AVAILABLE' },
  { id: 'tbl-2', tableNumber: 'T-02', capacity: 4, section: 'INDOOR', status: 'OCCUPIED' },
  { id: 'tbl-3', tableNumber: 'T-03', capacity: 4, section: 'INDOOR', status: 'AVAILABLE' },
  { id: 'tbl-4', tableNumber: 'T-04', capacity: 6, section: 'INDOOR', status: 'BILLING' },
  { id: 'tbl-5', tableNumber: 'VIP-01', capacity: 8, section: 'VIP_ROYAL', status: 'RESERVED' },
  { id: 'tbl-6', tableNumber: 'VIP-02', capacity: 12, section: 'VIP_ROYAL', status: 'AVAILABLE' },
  { id: 'tbl-7', tableNumber: 'TR-01', capacity: 4, section: 'TERRACE', status: 'AVAILABLE' },
  { id: 'tbl-8', tableNumber: 'TR-02', capacity: 4, section: 'TERRACE', status: 'OCCUPIED' },
  { id: 'tbl-9', tableNumber: 'GDN-01', capacity: 6, section: 'GARDEN', status: 'AVAILABLE' },
  { id: 'tbl-10', tableNumber: 'GDN-02', capacity: 6, section: 'GARDEN', status: 'AVAILABLE' },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Farhan Rahman',
    phone: '01711223344',
    email: 'farhan.r@gmail.com',
    tier: 'ROYAL',
    pointsBalance: 1250,
    totalSpent: 92400,
    visitCount: 28,
    joinedAt: '2025-01-15T10:00:00.000Z',
    notes: 'Prefers VIP-01, allergic to shellfish. VIP Guest.',
  },
  {
    id: 'cust-2',
    name: 'Nusrat Jahan',
    phone: '01819876543',
    email: 'nusrat.jahan@hotmail.com',
    tier: 'GOLD',
    pointsBalance: 580,
    totalSpent: 42000,
    visitCount: 14,
    joinedAt: '2025-04-10T14:30:00.000Z',
    notes: 'Loves Shahi Tukda and extra spicy grill.',
  },
  {
    id: 'cust-3',
    name: 'Tanvir Ahmed',
    phone: '01912345678',
    email: 'tanvir.ahmed@yahoo.com',
    tier: 'SILVER',
    pointsBalance: 240,
    totalSpent: 16500,
    visitCount: 6,
    joinedAt: '2025-08-01T18:00:00.000Z',
  },
  {
    id: 'cust-4',
    name: 'Sadia Islam',
    phone: '01678123456',
    email: 'sadia.islam@gmail.com',
    tier: 'BRONZE',
    pointsBalance: 85,
    totalSpent: 4800,
    visitCount: 2,
    joinedAt: '2026-02-14T19:00:00.000Z',
  },
];
